// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/objects"
)

// APIKeyProfileTemplateCreate is the builder for creating a APIKeyProfileTemplate entity.
type APIKeyProfileTemplateCreate struct {
	config
	mutation *APIKeyProfileTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyProfileTemplateCreate) SetCreatedAt(v time.Time) *APIKeyProfileTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyProfileTemplateCreate) SetNillableCreatedAt(v *time.Time) *APIKeyProfileTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyProfileTemplateCreate) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyProfileTemplateCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyProfileTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *APIKeyProfileTemplateCreate) SetDeletedAt(v int) *APIKeyProfileTemplateCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *APIKeyProfileTemplateCreate) SetNillableDeletedAt(v *int) *APIKeyProfileTemplateCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *APIKeyProfileTemplateCreate) SetName(v string) *APIKeyProfileTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *APIKeyProfileTemplateCreate) SetDescription(v string) *APIKeyProfileTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *APIKeyProfileTemplateCreate) SetNillableDescription(v *string) *APIKeyProfileTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *APIKeyProfileTemplateCreate) SetProjectID(v int) *APIKeyProfileTemplateCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetProfile sets the "profile" field.
func (_c *APIKeyProfileTemplateCreate) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateCreate {
	_c.mutation.SetProfile(v)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *APIKeyProfileTemplateCreate) SetProject(v *Project) *APIKeyProfileTemplateCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the APIKeyProfileTemplateMutation object of the builder.
func (_c *APIKeyProfileTemplateCreate) Mutation() *APIKeyProfileTemplateMutation {
	return _c.mutation
}

// Save creates the APIKeyProfileTemplate in the database.
func (_c *APIKeyProfileTemplateCreate) Save(ctx context.Context) (*APIKeyProfileTemplate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyProfileTemplateCreate) SaveX(ctx context.Context) *APIKeyProfileTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyProfileTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyProfileTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyProfileTemplateCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if apikeyprofiletemplate.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplate.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if apikeyprofiletemplate.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplate.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := apikeyprofiletemplate.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := apikeyprofiletemplate.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Profile(); !ok {
		v := apikeyprofiletemplate.DefaultProfile
		_c.mutation.SetProfile(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyProfileTemplateCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "APIKeyProfileTemplate.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "APIKeyProfileTemplate.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "APIKeyProfileTemplate.description"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "APIKeyProfileTemplate.project_id"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "APIKeyProfileTemplate.project"`)}
	}
	return nil
}

func (_c *APIKeyProfileTemplateCreate) sqlSave(ctx context.Context) (*APIKeyProfileTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyProfileTemplateCreate) createSpec() (*APIKeyProfileTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyProfileTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeyprofiletemplate.Table, sqlgraph.NewFieldSpec(apikeyprofiletemplate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Profile(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldProfile, field.TypeJSON, value)
		_node.Profile = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyprofiletemplate.ProjectTable,
			Columns: []string{apikeyprofiletemplate.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyProfileTemplate.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyProfileTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyProfileTemplateUpsertOne {
	_c.conflict = opts
	return &APIKeyProfileTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateCreate) OnConflictColumns(columns ...string) *APIKeyProfileTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyProfileTemplateUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyProfileTemplateUpsertOne is the builder for "upsert"-ing
	//  one APIKeyProfileTemplate node.
	APIKeyProfileTemplateUpsertOne struct {
		create *APIKeyProfileTemplateCreate
	}

	// APIKeyProfileTemplateUpsert is the "OnConflict" setter.
	APIKeyProfileTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyProfileTemplateUpsert) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateUpsert {
	u.Set(apikeyprofiletemplate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsert) UpdateUpdatedAt() *APIKeyProfileTemplateUpsert {
	u.SetExcluded(apikeyprofiletemplate.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *APIKeyProfileTemplateUpsert) SetDeletedAt(v int) *APIKeyProfileTemplateUpsert {
	u.Set(apikeyprofiletemplate.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsert) UpdateDeletedAt() *APIKeyProfileTemplateUpsert {
	u.SetExcluded(apikeyprofiletemplate.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *APIKeyProfileTemplateUpsert) AddDeletedAt(v int) *APIKeyProfileTemplateUpsert {
	u.Add(apikeyprofiletemplate.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *APIKeyProfileTemplateUpsert) SetName(v string) *APIKeyProfileTemplateUpsert {
	u.Set(apikeyprofiletemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsert) UpdateName() *APIKeyProfileTemplateUpsert {
	u.SetExcluded(apikeyprofiletemplate.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *APIKeyProfileTemplateUpsert) SetDescription(v string) *APIKeyProfileTemplateUpsert {
	u.Set(apikeyprofiletemplate.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsert) UpdateDescription() *APIKeyProfileTemplateUpsert {
	u.SetExcluded(apikeyprofiletemplate.FieldDescription)
	return u
}

// SetProfile sets the "profile" field.
func (u *APIKeyProfileTemplateUpsert) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateUpsert {
	u.Set(apikeyprofiletemplate.FieldProfile, v)
	return u
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsert) UpdateProfile() *APIKeyProfileTemplateUpsert {
	u.SetExcluded(apikeyprofiletemplate.FieldProfile)
	return u
}

// ClearProfile clears the value of the "profile" field.
func (u *APIKeyProfileTemplateUpsert) ClearProfile() *APIKeyProfileTemplateUpsert {
	u.SetNull(apikeyprofiletemplate.FieldProfile)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyProfileTemplateUpsertOne) UpdateNewValues() *APIKeyProfileTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeyprofiletemplate.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(apikeyprofiletemplate.FieldProjectID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyProfileTemplateUpsertOne) Ignore() *APIKeyProfileTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyProfileTemplateUpsertOne) DoNothing() *APIKeyProfileTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyProfileTemplateCreate.OnConflict
// documentation for more info.
func (u *APIKeyProfileTemplateUpsertOne) Update(set func(*APIKeyProfileTemplateUpsert)) *APIKeyProfileTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyProfileTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyProfileTemplateUpsertOne) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertOne) UpdateUpdatedAt() *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *APIKeyProfileTemplateUpsertOne) SetDeletedAt(v int) *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *APIKeyProfileTemplateUpsertOne) AddDeletedAt(v int) *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertOne) UpdateDeletedAt() *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *APIKeyProfileTemplateUpsertOne) SetName(v string) *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertOne) UpdateName() *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *APIKeyProfileTemplateUpsertOne) SetDescription(v string) *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertOne) UpdateDescription() *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateDescription()
	})
}

// SetProfile sets the "profile" field.
func (u *APIKeyProfileTemplateUpsertOne) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertOne) UpdateProfile() *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateProfile()
	})
}

// ClearProfile clears the value of the "profile" field.
func (u *APIKeyProfileTemplateUpsertOne) ClearProfile() *APIKeyProfileTemplateUpsertOne {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.ClearProfile()
	})
}

// Exec executes the query.
func (u *APIKeyProfileTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyProfileTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyProfileTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyProfileTemplateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyProfileTemplateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyProfileTemplateCreateBulk is the builder for creating many APIKeyProfileTemplate entities in bulk.
type APIKeyProfileTemplateCreateBulk struct {
	config
	err      error
	builders []*APIKeyProfileTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyProfileTemplate entities in the database.
func (_c *APIKeyProfileTemplateCreateBulk) Save(ctx context.Context) ([]*APIKeyProfileTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyProfileTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyProfileTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyProfileTemplateCreateBulk) SaveX(ctx context.Context) []*APIKeyProfileTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyProfileTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyProfileTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyProfileTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyProfileTemplateUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyProfileTemplateUpsertBulk {
	_c.conflict = opts
	return &APIKeyProfileTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyProfileTemplateCreateBulk) OnConflictColumns(columns ...string) *APIKeyProfileTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyProfileTemplateUpsertBulk{
		create: _c,
	}
}

// APIKeyProfileTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyProfileTemplate nodes.
type APIKeyProfileTemplateUpsertBulk struct {
	create *APIKeyProfileTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyProfileTemplateUpsertBulk) UpdateNewValues() *APIKeyProfileTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeyprofiletemplate.FieldCreatedAt)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(apikeyprofiletemplate.FieldProjectID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyProfileTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyProfileTemplateUpsertBulk) Ignore() *APIKeyProfileTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyProfileTemplateUpsertBulk) DoNothing() *APIKeyProfileTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyProfileTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyProfileTemplateUpsertBulk) Update(set func(*APIKeyProfileTemplateUpsert)) *APIKeyProfileTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyProfileTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyProfileTemplateUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertBulk) UpdateUpdatedAt() *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *APIKeyProfileTemplateUpsertBulk) SetDeletedAt(v int) *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *APIKeyProfileTemplateUpsertBulk) AddDeletedAt(v int) *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertBulk) UpdateDeletedAt() *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *APIKeyProfileTemplateUpsertBulk) SetName(v string) *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertBulk) UpdateName() *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *APIKeyProfileTemplateUpsertBulk) SetDescription(v string) *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertBulk) UpdateDescription() *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateDescription()
	})
}

// SetProfile sets the "profile" field.
func (u *APIKeyProfileTemplateUpsertBulk) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *APIKeyProfileTemplateUpsertBulk) UpdateProfile() *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.UpdateProfile()
	})
}

// ClearProfile clears the value of the "profile" field.
func (u *APIKeyProfileTemplateUpsertBulk) ClearProfile() *APIKeyProfileTemplateUpsertBulk {
	return u.Update(func(s *APIKeyProfileTemplateUpsert) {
		s.ClearProfile()
	})
}

// Exec executes the query.
func (u *APIKeyProfileTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyProfileTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyProfileTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyProfileTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
