// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/objects"
)

// APIKeyProfileTemplate is the model entity for the APIKeyProfileTemplate schema.
type APIKeyProfileTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Template name
	Name string `json:"name,omitempty"`
	// Template description
	Description string `json:"description,omitempty"`
	// Project ID, set via project edge
	ProjectID int `json:"project_id,omitempty"`
	// Profile holds the value of the "profile" field.
	Profile *objects.APIKeyProfile `json:"profile,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIKeyProfileTemplateQuery when eager-loading is set.
	Edges        APIKeyProfileTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIKeyProfileTemplateEdges holds the relations/edges for other nodes in the graph.
type APIKeyProfileTemplateEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyProfileTemplateEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyProfileTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyprofiletemplate.FieldProfile:
			values[i] = new([]byte)
		case apikeyprofiletemplate.FieldID, apikeyprofiletemplate.FieldDeletedAt, apikeyprofiletemplate.FieldProjectID:
			values[i] = new(sql.NullInt64)
		case apikeyprofiletemplate.FieldName, apikeyprofiletemplate.FieldDescription:
			values[i] = new(sql.NullString)
		case apikeyprofiletemplate.FieldCreatedAt, apikeyprofiletemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyProfileTemplate fields.
func (_m *APIKeyProfileTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyprofiletemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case apikeyprofiletemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyprofiletemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeyprofiletemplate.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case apikeyprofiletemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case apikeyprofiletemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case apikeyprofiletemplate.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case apikeyprofiletemplate.FieldProfile:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Profile); err != nil {
					return fmt.Errorf("unmarshal field profile: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyProfileTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyProfileTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the APIKeyProfileTemplate entity.
func (_m *APIKeyProfileTemplate) QueryProject() *ProjectQuery {
	return NewAPIKeyProfileTemplateClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this APIKeyProfileTemplate.
// Note that you need to call APIKeyProfileTemplate.Unwrap() before calling this method if this APIKeyProfileTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyProfileTemplate) Update() *APIKeyProfileTemplateUpdateOne {
	return NewAPIKeyProfileTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyProfileTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyProfileTemplate) Unwrap() *APIKeyProfileTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyProfileTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyProfileTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyProfileTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("profile=")
	builder.WriteString(fmt.Sprintf("%v", _m.Profile))
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyProfileTemplates is a parsable slice of APIKeyProfileTemplate.
type APIKeyProfileTemplates []*APIKeyProfileTemplate
