// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// APIKeyProfileTemplateDelete is the builder for deleting a APIKeyProfileTemplate entity.
type APIKeyProfileTemplateDelete struct {
	config
	hooks    []Hook
	mutation *APIKeyProfileTemplateMutation
}

// Where appends a list predicates to the APIKeyProfileTemplateDelete builder.
func (_d *APIKeyProfileTemplateDelete) Where(ps ...predicate.APIKeyProfileTemplate) *APIKeyProfileTemplateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *APIKeyProfileTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyProfileTemplateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *APIKeyProfileTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apikeyprofiletemplate.Table, sqlgraph.NewFieldSpec(apikeyprofiletemplate.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// APIKeyProfileTemplateDeleteOne is the builder for deleting a single APIKeyProfileTemplate entity.
type APIKeyProfileTemplateDeleteOne struct {
	_d *APIKeyProfileTemplateDelete
}

// Where appends a list predicates to the APIKeyProfileTemplateDelete builder.
func (_d *APIKeyProfileTemplateDeleteOne) Where(ps ...predicate.APIKeyProfileTemplate) *APIKeyProfileTemplateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *APIKeyProfileTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apikeyprofiletemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyProfileTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
