// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/apikeyprofiletemplate"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// APIKeyProfileTemplateUpdate is the builder for updating APIKeyProfileTemplate entities.
type APIKeyProfileTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *APIKeyProfileTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the APIKeyProfileTemplateUpdate builder.
func (_u *APIKeyProfileTemplateUpdate) Where(ps ...predicate.APIKeyProfileTemplate) *APIKeyProfileTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyProfileTemplateUpdate) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIKeyProfileTemplateUpdate) SetDeletedAt(v int) *APIKeyProfileTemplateUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIKeyProfileTemplateUpdate) SetNillableDeletedAt(v *int) *APIKeyProfileTemplateUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *APIKeyProfileTemplateUpdate) AddDeletedAt(v int) *APIKeyProfileTemplateUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *APIKeyProfileTemplateUpdate) SetName(v string) *APIKeyProfileTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIKeyProfileTemplateUpdate) SetNillableName(v *string) *APIKeyProfileTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APIKeyProfileTemplateUpdate) SetDescription(v string) *APIKeyProfileTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APIKeyProfileTemplateUpdate) SetNillableDescription(v *string) *APIKeyProfileTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProfile sets the "profile" field.
func (_u *APIKeyProfileTemplateUpdate) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateUpdate {
	_u.mutation.SetProfile(v)
	return _u
}

// ClearProfile clears the value of the "profile" field.
func (_u *APIKeyProfileTemplateUpdate) ClearProfile() *APIKeyProfileTemplateUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// Mutation returns the APIKeyProfileTemplateMutation object of the builder.
func (_u *APIKeyProfileTemplateUpdate) Mutation() *APIKeyProfileTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyProfileTemplateUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyProfileTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyProfileTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyProfileTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyProfileTemplateUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if apikeyprofiletemplate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyProfileTemplateUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyProfileTemplate.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *APIKeyProfileTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *APIKeyProfileTemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *APIKeyProfileTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyprofiletemplate.Table, apikeyprofiletemplate.Columns, sqlgraph.NewFieldSpec(apikeyprofiletemplate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(apikeyprofiletemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Profile(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldProfile, field.TypeJSON, value)
	}
	if _u.mutation.ProfileCleared() {
		_spec.ClearField(apikeyprofiletemplate.FieldProfile, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyprofiletemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyProfileTemplateUpdateOne is the builder for updating a single APIKeyProfileTemplate entity.
type APIKeyProfileTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *APIKeyProfileTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyProfileTemplateUpdateOne) SetUpdatedAt(v time.Time) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIKeyProfileTemplateUpdateOne) SetDeletedAt(v int) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIKeyProfileTemplateUpdateOne) SetNillableDeletedAt(v *int) *APIKeyProfileTemplateUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *APIKeyProfileTemplateUpdateOne) AddDeletedAt(v int) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *APIKeyProfileTemplateUpdateOne) SetName(v string) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIKeyProfileTemplateUpdateOne) SetNillableName(v *string) *APIKeyProfileTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APIKeyProfileTemplateUpdateOne) SetDescription(v string) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APIKeyProfileTemplateUpdateOne) SetNillableDescription(v *string) *APIKeyProfileTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProfile sets the "profile" field.
func (_u *APIKeyProfileTemplateUpdateOne) SetProfile(v *objects.APIKeyProfile) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.SetProfile(v)
	return _u
}

// ClearProfile clears the value of the "profile" field.
func (_u *APIKeyProfileTemplateUpdateOne) ClearProfile() *APIKeyProfileTemplateUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// Mutation returns the APIKeyProfileTemplateMutation object of the builder.
func (_u *APIKeyProfileTemplateUpdateOne) Mutation() *APIKeyProfileTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeyProfileTemplateUpdate builder.
func (_u *APIKeyProfileTemplateUpdateOne) Where(ps ...predicate.APIKeyProfileTemplate) *APIKeyProfileTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyProfileTemplateUpdateOne) Select(field string, fields ...string) *APIKeyProfileTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyProfileTemplate entity.
func (_u *APIKeyProfileTemplateUpdateOne) Save(ctx context.Context) (*APIKeyProfileTemplate, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyProfileTemplateUpdateOne) SaveX(ctx context.Context) *APIKeyProfileTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyProfileTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyProfileTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyProfileTemplateUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if apikeyprofiletemplate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized apikeyprofiletemplate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := apikeyprofiletemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyProfileTemplateUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyProfileTemplate.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *APIKeyProfileTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *APIKeyProfileTemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *APIKeyProfileTemplateUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyProfileTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyprofiletemplate.Table, apikeyprofiletemplate.Columns, sqlgraph.NewFieldSpec(apikeyprofiletemplate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyProfileTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeyprofiletemplate.FieldID)
		for _, f := range fields {
			if !apikeyprofiletemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeyprofiletemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(apikeyprofiletemplate.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Profile(); ok {
		_spec.SetField(apikeyprofiletemplate.FieldProfile, field.TypeJSON, value)
	}
	if _u.mutation.ProfileCleared() {
		_spec.ClearField(apikeyprofiletemplate.FieldProfile, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &APIKeyProfileTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyprofiletemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
